### ISSUE TITLE
Not receiving notifications 

### ISSUE THREAD

**Issue by joshketellapper** [superfeedr/superfeedr-node#18]
I'm using the example but I changed the feed to http://superfeedr.com/dummy.xml and adding to it through the xmpp console but I'm not receiving notifications.

I uncommented the console.log statements. Subscribing is working.

**Comment by millette** [comment]
Try to add a "status" event listener equivlent to the "notification" one on line 17:
https://github.com/superfeedr/superfeedr-node/blob/master/examples/basic.js#L17

I just found out 90% of the pings I was getting where seen as statuses instead of notifications but both count the same way in terms of credits.

**Comment by julien51** [comment]
@joshketellapper would you be able to procide me with your superfeedr login so I can check directly?
